# Generated by Django 4.2 on 2024-08-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='artist_picture')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('release_year', models.DateField()),
                ('genre', models.CharField(choices=[('J', 'Jazz'), ('RK', 'Rock'), ('P', 'Pop'), ('H', 'Hip Hop'), ('C', 'Classic'), ('I', 'Indie'), ('M', 'Metal'), ('R', 'Rap'), ('E', 'Electronic')], max_length=15)),
                ('cover', models.ImageField(upload_to='album_covers')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_manager.artist')),
            ],
        ),
    ]
